/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ImageData {
  height: number
  width: number
  bytes: Buffer
}
export class Clipboard {
  constructor()
  setText(text: string): void
  getText(): string
  /** Returns a object contains raw RGBA pixels data buffer and size  */
  getImage(): ImageData
  /** RGBA bytes */
  setImage(width: number, height: number, image: Buffer): void
}
